version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: busbook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 000
      POSTGRES_HOST_AUTH_METHOD: "trust"

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/busbook
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 000
